### ISSUE TITLE
Create a "public" group with sysop-ish permissions

### ISSUE THREAD

**Issue by ftrain** [tildeclub/tilde.club#11]
it was inbetween sysop/sysadmin and user
and you could compile into /usr/public/bin
Or /usr/local/public/bin

Assigning to @djacobs just to put it here; implementation is tbd.

**Comment by mbuchholz81** [comment]
If there is any continuing issues related to this issue after all these years please let me know. 
Compilers are available for most languages on new server.  go language will be installed today to ensure things that were there are still available.
