### ISSUE TITLE
Consider running light caching nameserver on irc host

### ISSUE THREAD

**Issue by delfuego** [tildeclub/tilde.club#67]
Since `charybdis` relies entirely on DNS for IP-to-hostname resolution, and we have the IRC and shell servers talking over the private network, we'd need to run a light DNS server somewhere to resolve the private network IPs to names. Nothing is broken without it, but when users log into IRC and others see `delfuego [delfuego@172.30.0.176] has joined #tildeclub`, it'd clean up that host IP address part a bit (`delfuego [delfuego@tilde.club] has joined #tildeclub`).

**Comment by mbuchholz81** [comment]
5 years late but...

Moved over to inspircd and have linked IRC to the tilde.chat IRC network. So those issues shouldn't be an issue any longer.  enjoy.
