### ISSUE TITLE
Install Motsognir as a gopher server on tilde.club ?

### ISSUE THREAD

**Issue by vielmetti** [tildeclub/tilde.club#78]
I asked about the possibility of running a gopher server on tilde.club on the gopher-project mailing list, and received a reply from Mateusz Viste with an offer to help getting Motsognir (his gopher server) running.

http://sourceforge.net/projects/motsognir/ is the source code. 

I'll invite Mateusz here; it may be that this gets rolled into some puppet-tilde effort as well or instead, I don't know if the people on tildeclub feel a burning desire to support gopher or not (it doesn't support directly the "make cool web pages" goal, but it is period-appropriate).

thanks

Ed

**Comment by mbuchholz81** [comment]
5 years too late.  But there is now Gopher on tilde.club.   anyone with an account just needs to create a "public_gopher" and create a gophermap file which will be available at: Gopher://tilde.club/1/~username
New accounts coming soon.

Thanks

**Comment by gerwitz** [comment]
It's never too late.

Maybe it's just me, but my gophermap's info lines are sending their `I`. I cannot fathom how this could be, having read the Motsognir manual. But maybe we're running a different server?

(I'd love to lose that /1/ in the paths.)

**Comment by benharri** [comment]
We're running [gophernicus](https://github.com/gophernicus/gophernicus), which is not as strict. Gophermap documentation [here](https://github.com/gophernicus/gophernicus/blob/master/README.Gophermap).

There's no way to lose the `/1/` as the item type is a fundamental part of the gopher protocol.

**Comment by mateuszviste** [comment]
> Maybe it's just me, but my gophermap's info lines are sending their `i`:
> https://gopher.floodgap.com/gopher/gw?a=gopher%3A%2F%2Ftilde.club%2F1%2F%7Egerwitz

My guess is that this is not a Motsognir installation. Probably some other gopher server that does not understand 'i' items, and expects text lines to start without any itemtype. Simply try removing these 'i' characters...

> (I'd also love to lose that /1/ in the paths.)

That's not possible, gopher URLs must have an explicit itemtype. The only exception is the server's root folder, where '1' is assumed.
