### ISSUE TITLE
Find a Co-Wrangler, Documentation [HelpWanted]

### ISSUE THREAD

**Issue by ftrain** [tildeclub/tilde.club#84]
I (@ftrain) want to wrangle the docs. There are docs all over the place. I want to start using tilde.club as a teaching environment to do web page workshops, and I'm starting with the docs. I'd love a co-wrangler.

**Comment by benharri** [comment]
If you're wondering why this is closed, I've started moving docs to our [self-hosted wiki](https://tilde.club/wiki/). It's still markdown based and can be updated by anyone via PR to the [tildeclub/site repo](https://github.com/tildeclub/site/tree/master/wiki).
