### ISSUE TITLE
Find a Tilde Cartographer [HelpWanted]

### ISSUE THREAD

**Issue by ftrain** [tildeclub/tilde.club#85]
How can we explore tilde sites? I truly have no idea. Lists are okay but it's all getting big. I love poking around and seeing what people are doing and would love some paths.

**Comment by williamjacksn** [comment]
@brennen Has someone already implemented `tilde.json`, &c.? Is there already a spec or do we need to come up with one?

**Comment by brennen** [comment]
Hey @williamjacksn - I've kinda got reference versions of files / utilities for this:

- http://squiggle.city/tilde.json
- http://squiggle.city/users.txt
- http://squiggle.city/tilde.txt

...and some stuff in [the squiggle.city repo](https://github.com/squigglecity/squiggle.city), and I think the protocol.club folks may have come up with a spec that'd be pretty easy to make these conform with. Bit busy at the moment, but I can see about tidying that stuff.

**Comment by pfhawkins** [comment]
Here's what I know that protocol.club has cooked up:

- http://protocol.club/~datagrok/beta-wiki/tdp.html
- http://protocol.club/~axylos/async_msg.html

I'm not sure what if any tooling has been cooked up around either of those.

**Comment by williamjacksn** [comment]
Ha, I wrote http://protocol.club/~datagrok/beta-wiki/tdp.html but didn't implement it. I am going to work on some scripts to generate these documents.

**Comment by pfhawkins** [comment]
:+1:

**Comment by williamjacksn** [comment]
I now have some tools to generate these documents:

https://github.com/williamjacksn/tilde-description-protocol

`tilde_server.py` is an interactive script that asks questions then generates the server info document based on the answers. This document should be fairly static.

`tilde_users.py` is an automated script that generates the user list document.

My best guess for a home in this repo is in the `api` folder.
