### ISSUE TITLE
Send/Accept Passwords

### ISSUE THREAD

**Issue by tsangiotis** [tildeclub/tilde.club#87]
I create a tilde-like server and the [irc instructions](https://github.com/tildeclub/tilde.irc), prompt me to create an issue here. 

Some help? :)

**Comment by michaelcoyote** [comment]
What password?  There seems to be a password for the ircd in here.  I would change that to reflect your own local password choice.
https://github.com/tildeclub/tilde.irc/blob/master/conf/ircd.conf#L236

As for the ssh password, I would look at the documentation for the phusion image that the Dockerfile sources.

https://github.com/phusion/baseimage-docker#login_ssh

**Comment by delfuego** [comment]
If you want to set up your own tilde.net IRC server, the docs to walk you through it are here:

https://github.com/tildeclub/tilde.club/tree/master/docs

There's also a Dockerized IRC server that will automatically connect to our network (once we set up the relevant config for your server at our end):

https://github.com/tildeclub/tilde.irc

**Comment by tsagi** [comment]
I did use the Dockerized IRC server. The instructions there mention to file an issue here:

> - docker server Edit the ircd.env file, replacing the five variables with the correct values.
>
>     ...
>     - For the `CONNECT_TILDE_SEND_PASSWORD` and `CONNECT_TILDE_ACCEPT_PASSWORD`, you need to coordinate these values with us (probably the best way is to [file an issue](https://github.com/tildeclub/tilde.club/issues)).

**Comment by mbuchholz81** [comment]
Need to know the status of this issue, If its a non-issue after all these years I am going to close it. 

Thanks
