### ISSUE TITLE
Announce grand re-opening of tilde.club

### ISSUE THREAD

**Issue by vielmetti** [tildeclub/tilde.club#90]
Looks like we are back under steam again, let's get the word out when we're ready.

**Comment by mbuchholz81** [comment]
We definitely  are :)   things are happening.  Plan to re-open registrations in about a week.  Going to be emailing everyone on the wait list hopefully today.

Thanks :)

**Comment by mbuchholz81** [comment]
Anyone that has access to tilde.club currently can join us in #club on IRC by typing "chat" in the terminal.  Hope to see more of you there :)

**Comment by mbuchholz81** [comment]
@vielmetti   We have technically re-opened already.   Will be opening signups to anyone on the 20th of this month.  Very exciting.

**Comment by benharri** [comment]
I'll draft an announcement post to put on the homepage

**Comment by mbuchholz81** [comment]
> 
> 
> I'll draft an announcement post to put on the homepage
@benharri  Sorry guess I should have looked on here first.

**Comment by benharri** [comment]
Announcement posted on the homepage as of [19c91c4](https://github.com/tildeclub/site/commit/19c91c40330c92f03f4130e3d7a5055a0b80fb1e#diff-828e0013b8f3bc1bb22b4f57172b019d).
