### ISSUE TITLE
Set up an innd

### ISSUE THREAD

**Issue by benharri** [tildeclub/tilde.club#92]
I've provisioned a vm and enlisted the help of @ox

**Comment by ox** [comment]
What groups should be created? The ancient log `.newsrc` file I have lists:

```
    tilde.blogs
    tilde.club
    tilde.foo
    tilde.food+drink
    tilde.general
    tilde.meetups
    tilde.projects
    tilde.test
    tilde.town
    tilde.town.poetry
    tilde.town.python
    tilde.webhistory
```

Is there some hierarchy that's preferable?

**Comment by benharri** [comment]
Should we incorporate the [tildeverse members](https://tildeverse.org/members/)?

There's also a (somewhat-unmaintained) tildeverse [nntp effort](https://news.tildeverse.org), which might be worth extending or replacing.

**Comment by mbuchholz81** [comment]
@ox  @benharri   Maybe could include some that are listed on https://news.tildeverse.org

**Comment by michaelcoyote** [comment]
@benharri I think it's probably good to plan on possibly extending the network and/or adding it to an existing network, but NNTP is one of those things that I'd really like to see come back soon.

**Comment by mbuchholz81** [comment]
@michaelcoyote  it is currently in progress as we speak :)

**Comment by benharri** [comment]
@ox where is this at? I'm currently seeing the "you don't have permission to talk" errors.

**Comment by jamestomasino** [comment]
cosmic.voyage is set up in an attempt to peer with club as well. Also getting "you don't have permission to talk" errors for now.

**Comment by ox** [comment]
I got local posting working (from news.tilde.club) and it can pull messages for topics from tilde.town. Still working on getting the `readers.conf` set up right to figure out authentication for users connecting from tilde.club. I think it's right but it's very finicky. I'll try to carve out some more time this week to test more.

**Comment by ox** [comment]
A small tweak in the `readers.conf` seemed to have opened up connections from tilde.club. There is some weird behavior where fetching news from tilde.club results in a lot of `[Connection failed to news.tilde.club,119: Connection timed out]`, but most operations seem to work? I can list groups to add, view messages, and reply to topics. Any ideas?

**Comment by ox** [comment]
> cosmic.voyage is set up in an attempt to peer with club as well. Also getting "you don't have permission to talk" errors for now.

I saw your message! I'll try to set up sending messages to y'all as well. Is the news sever at `cosmic.voyage`?

Is there a way I can see your readers.conf and incoming.conf?

**Comment by benharri** [comment]
Here's the relevant configs from tilde.team (I think?):

incoming.conf:
```
peer club {
  hostname:         "news.tilde.club"
}
```

readers.conf:
```
auth "tildeverse" {
    hosts: "news.tildeverse.org, 142.44.251.173, cosmic.voyage, 104.238.186.103, tilde.team, 51.79.32.48, tilde.club, 149.56.184.114, news.tilde.club, 51.79.32.53"
    default: "<tildeverse>"
}
access "tildeverse" {
    users: "<tildeverse>"
    newsgroups: "*"
    access: RPA
}
```

**Comment by ox** [comment]
@benharri Woah, admin access for everyone?

**Comment by benharri** [comment]
Removing `access: RPA` would be the correct way, right?

**Comment by jamestomasino** [comment]
https://ttm.sh/my.conf - cosmic's incoming.conf.

my readers conf is all localhost stuff, so i  don't think it'll help you.

**Comment by jamestomasino** [comment]
You can find pretty much everything I did to set up cosmic on my gopher hole here:

gopher://gopher.black/1/phlog/20190426-net-news-on-cosmic-voyage

**Comment by ox** [comment]
> Removing `access: RPA` would be the correct way, right?

`access: RP` would allow (R)eading and (P)osting. A is admin

**Comment by benharri** [comment]
Ok, I've set it to `access: RP`

**Comment by deepend-tildeclub** [comment]
@ox @benharri   Is this currently functional for tilde.club to use or is it still in progress? 

Thanks

**Comment by ox** [comment]
Hey! I’ve been working on it and mostly struggling getting the access right so that only users of tilde.club can access and post on the service. The connection addresses are ipv6 sometimes, but the reverse lookup stopped returning `tilde.club` as the host. Not sure what changed.


________________________________

**Comment by benharri** [comment]
Sorry, I moved the vm to a different physical host. I don't think there's an ipv6 dns record for news.tilde.club, and i haven't configured ipv6 properly yet, so I'm not sure how it'd be connecting that way.

**Comment by deepend-tildeclub** [comment]
yeah.. ipv6 should be completely gone from news.tilde.club :)    reverse dns shouldn't be any issue unless the dns server that VM is using is glitchy?

**Comment by ox** [comment]
When I connect to tilde.club and connect to news.tilde.club the remote connection is ipv6.


________________________________

**Comment by deepend-tildeclub** [comment]
Shouldn't be.  IPV6 was removed from the dns.  So it shouldn't.. But i see it is still resolving on tilde.club.  Probably something weird with the dns server we use. I have found that my   .tilde dns server doesn't refresh often enough.

Will fix right now and let you know.

Thanks

**Comment by deepend-tildeclub** [comment]
@ox tilde.club should resolve news.tilde.club properly now.  

Thanks

**Comment by deepend-tildeclub** [comment]
@ox let me know if things helped with the access rights issue. 

Thanks :D

**Comment by ox** [comment]
Well...now I can't seem to ssh to news.tilde.club 😰. ssh is stuck trying to connect to 51.79.32.53. Is there a new IP?

**Comment by deepend-tildeclub** [comment]
@ox  thats not the right ip anymore. It moved.   192.95.3.23  is the new ip.. or connect to news.tilde.club using its subdomain :)
