### ISSUE TITLE
Set up a fingerd (preferably efingerd)

### ISSUE THREAD

**Issue by mbuchholz81** [tildeclub/tilde.club#93]
Currently was testing fingerd on the server, not configurable enough for our needs.   Need to compile efingerd.

**Comment by michaelcoyote** [comment]
Looks like the author (@garabik) is on GitHub, but sadly the efingerd source isn't. It is avalable as a tar.gz file [here](http://kassiopeia.juls.savba.sk/~garabik/software/efingerd/)
 It might be good to keep a version of it in a git repo for easy hacking and easy access for other tildes

**Comment by mbuchholz81** [comment]
@michaelcoyote doesn't seem to like the libident thats on the server.  Not sure what version it is wanting ?

**Comment by benharri** [comment]
Somehow I got it to compile and running. Try `finger @tilde.chat`.

**Comment by michaelcoyote** [comment]
@benharri what was the trick you used to get it working?

**Comment by benharri** [comment]
I grabbed the debian source bundle with `apt-get source efingerd`, tar'd it up and built it on ~club... I think @mbuchholz81 copied something over to address a missing `libident.a` lib but it works now. 

I also adjusted the systemd service file from fedora's finger-server package to point to my new efingerd binary. (see `/usr/lib/systemd/system/finger.socket` and `/usr/lib/systemd/system/finger@.service`)
